-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`SCHOOL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SCHOOL` (
  `IDT_SCHOOL` INT NOT NULL,
  `NAM_SCHOOL` VARCHAR(45) NOT NULL,
  `LAT_LOC_SCHOOL` DOUBLE NOT NULL,
  `LON_LOC_SCHOOL` DOUBLE NOT NULL,
  `SUF_SCHOOL` VARCHAR(45) NOT NULL COMMENT 'SUFFIX OF SCHOOL EMAIL',
  PRIMARY KEY (`IDT_SCHOOL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USER` (
  `IDT_USER` INT NOT NULL,
  `PMS_USER` INT NOT NULL COMMENT '1: SCHOOL\n2: STUDENTS\n3: ORGANIZATIONS',
  `NAM_USER` VARCHAR(45) NOT NULL,
  `PSW_USER` VARCHAR(45) NOT NULL,
  `EML_USER` VARCHAR(45) NOT NULL COMMENT 'User email (only suffix .edu)',
  `CPN_USER` VARCHAR(45) NULL COMMENT 'CELLPHONE NUMBER OF USER',
  `SND_EML_USER` VARCHAR(45) NULL,
  `IMG_USER` VARCHAR(45) NULL,
  `SCHOOL_IDT_SCHOOL` INT NULL,
  PRIMARY KEY (`IDT_USER`),
  INDEX `fk_USER_SCHOOL1_idx` (`SCHOOL_IDT_SCHOOL` ASC),
  CONSTRAINT `fk_USER_SCHOOL1`
    FOREIGN KEY (`SCHOOL_IDT_SCHOOL`)
    REFERENCES `mydb`.`SCHOOL` (`IDT_SCHOOL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EVENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EVENT` (
  `IDT_EVENT` INT NOT NULL,
  `NAM_EVENT` VARCHAR(45) NOT NULL,
  `DAT_EVENT` DATETIME NOT NULL,
  `PRC_EVENT` DOUBLE NOT NULL,
  `LAT_LOC_EVENT` DOUBLE NULL,
  `LON_LOC_EVENT` DOUBLE NULL,
  `LNK_EVENT` VARCHAR(45) NULL,
  PRIMARY KEY (`IDT_EVENT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CREATOR_EVENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CREATOR_EVENT` (
  `IDT_USER_EVENT` INT NOT NULL,
  `USER_IDT_USER` INT NOT NULL,
  `EVENT_IDT_EVENT` INT NOT NULL,
  `DAT_USER_EVENT` DATETIME NOT NULL COMMENT 'WHEN THE EVENT WAS CREATED BY USER.',
  PRIMARY KEY (`IDT_USER_EVENT`),
  INDEX `fk_USER_EVENT_USER_idx` (`USER_IDT_USER` ASC),
  INDEX `fk_USER_EVENT_EVENT1_idx` (`EVENT_IDT_EVENT` ASC),
  CONSTRAINT `fk_USER_EVENT_USER`
    FOREIGN KEY (`USER_IDT_USER`)
    REFERENCES `mydb`.`USER` (`IDT_USER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_EVENT_EVENT1`
    FOREIGN KEY (`EVENT_IDT_EVENT`)
    REFERENCES `mydb`.`EVENT` (`IDT_EVENT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER_EVENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USER_EVENT` (
  `IDT_USER_EVENT` INT NOT NULL,
  `USER_IDT_USER` INT NOT NULL,
  `EVENT_IDT_EVENT` INT NOT NULL,
  `SND_MSG_EVENT` TINYINT(1) NOT NULL COMMENT '1: TEXT ME WHEN EVENT IS NEAR TO START\n0: DON\'T TEXT ME',
  `WHN_TXT_EVENT` DATETIME NULL COMMENT 'WHEN TEXT USER ABOUT THE EVENT: OPTIONS ARE\n1 DAY BEFORE THE EVENT\n8 HOURS BEFORE EVENT\n2 HOURS BEFORE EVENT',
  PRIMARY KEY (`IDT_USER_EVENT`),
  INDEX `fk_USER_EVENT_USER1_idx` (`USER_IDT_USER` ASC),
  INDEX `fk_USER_EVENT_EVENT2_idx` (`EVENT_IDT_EVENT` ASC),
  CONSTRAINT `fk_USER_EVENT_USER1`
    FOREIGN KEY (`USER_IDT_USER`)
    REFERENCES `mydb`.`USER` (`IDT_USER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_EVENT_EVENT2`
    FOREIGN KEY (`EVENT_IDT_EVENT`)
    REFERENCES `mydb`.`EVENT` (`IDT_EVENT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'ROOT_ADSCHOOL' IDENTIFIED BY 'root';

GRANT ALL ON `mydb`.* TO 'ROOT_ADSCHOOL';
CREATE USER 'APP_ADSCHOOL' IDENTIFIED BY 'app';

GRANT SELECT, INSERT, TRIGGER ON TABLE `mydb`.* TO 'APP_ADSCHOOL';
GRANT SELECT ON TABLE `mydb`.* TO 'APP_ADSCHOOL';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `mydb`.* TO 'APP_ADSCHOOL';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
